### ISSUE TITLE
IBDesignables: Failed to update auto layout status: Failed to load desginables from path (null)

### ISSUE THREAD

**Issue by ishaq** [glaszig/SZTextView#35]
![screenshot 2015-04-03 16 15 38](https://cloud.githubusercontent.com/assets/75963/6981554/e7da6d34-da1c-11e4-8c35-663d9317e5d2.png)

Xcode **6.2 (6C141e)**
OSX **10.10.3**

**Comment by glaszig** [comment]
i haven't had the chance to get hold of a 10.10 machine, yet. however, please try using a newer cocoapods as described in [this stackoverflow](http://stackoverflow.com/a/28108248) and let me know.

**Comment by ishaq** [comment]
Thanks, I missed your original email somehow. My Bad! I had seen the SO thread earlier but incorrectly assumed that use_frameworks! was a temporary fix. Sorry about that.
