### ISSUE TITLE
Input marker set back to index 0 when autocomplete is active and textView is touched

### ISSUE THREAD

**Issue by FrostRocket** [glaszig/SZTextView#41]
Having an issue as described in the subject line.  If you start inputting a word and autocorrect offers a suggestion, tap the textview again and it will always move the cursor index back to 0.

For example:

1. Receive focus to text view.
2. Start typing "Cj".
3. Autocomplete should offer "Check" for word suggestion.
4. Tap text view again to "accept" recommendation.

Result:

"Check" appears in the text view, but the cursor index is set back to the beginning.

**Comment by glaszig** [comment]
could not replicate on ios 9.2. if you're still having please post your ios version and reopen.
