### ISSUE TITLE
Doesn't work on iOS 9.0

### ISSUE THREAD

**Issue by CaesarPan** [glaszig/SZTextView#44]
The whole textView won't show.

**Comment by goktugyil** [comment]
why did you close this?

**Comment by CaesarPan** [comment]
I've worked out the issue.

**Comment by goktugyil** [comment]
how?

**Comment by glaszig** [comment]
@CaesarPan would you enlighten us, please?

**Comment by CaesarPan** [comment]
Cause it's my fault so it isn't a bug of this widget. But I've forgot how I addressed the issue. You may want to check your own code.
