### ISSUE TITLE
selectable  cause crash

### ISSUE THREAD

**Issue by codwam** [glaszig/SZTextView#45]
self.textView.selectable = NO;
And add a button to set textView text directly,like below
- (IBAction)changeAction:(id)sender {
    self.textView.text = @"sjldfjlksjdflksjdf";
}

This will be crashed and the console log:
2015-11-24 22:42:24.134 SZTextView[3336:137753] keyPath = attributedText, change = {
    kind = 1;
    new = "<null>";
}
2015-11-24 22:42:24.134 SZTextView[3336:137753] keyPath = text, change = {
    kind = 1;
    new = sjldfjlksjdflksjdf;
}
This can be solved but I don't know it's good or not:

        if (![newAttributedText isEqual:[NSNull null]]) {
            [self setPlaceholderVisibleForText:newAttributedText.string];
        }

**Comment by glaszig** [comment]
can't replicate in the demo app. please consider a demo yourself and reopen the issue.
