### ISSUE TITLE
Failed to load designable from path(null)

### ISSUE THREAD

**Issue by dleviathan** [glaszig/SZTextView#52]
I use your lib in storyboard (with iO7 and Objective-C) when i add your controller and imbue class to SZTextView i got this error

> Base.lproj/Main.storyboard: error: IB Designables: Failed to update auto layout status: Failed to load designables from path (null)

> Base.lproj/Main.storyboard: error: IB Designables: Failed to render instance of SZTextView: Failed to load designables from path (null)

how to fix it?

**Comment by glaszig** [comment]
which version of xcode are you running? are you using cocoapods? carthage? there was an issue with cocoapods... CocoaPods/CocoaPods#2792

**Comment by Nailer** [comment]
Getting the same error. Using cocoapods. XCode 7.3.1

It compiles, but it's annoying to have this error pop up in the project all the time.

I assume it's because I'm not using dynamic libraries (still need to support iOS7).

**Comment by atmikev** [comment]
Same. Xcode Version 7.3.1 (7D1014). Cocoapods 0.39.0

**Comment by glaszig** [comment]
the issue seems to be the combination of cocoapods + IB_DESIGNABLE (+ iOS 7).

please try to not use SZTextView via cocoapods but one of the following ways and report back.

- copy source files directly into your project
- add SZTextView as a git submodule
- carthage

**Comment by glaszig** [comment]
i just validated the issue with cocoapods 1.0.1.

**unless** your deployment target is iOS 7, the solution would be to add the `use_frameworks!` macro to your `Podfile`. the problem with iOS 7 is that dynamic frameworks, as [introduced in cocoapods 0.36][cocoapods] with `use_frameworks!`, technically work but will [likely be rejected upon submission][reject].

so, the only viable solution to have `IB_DESIGNABLE`s to work when developing for iOS 7 is to either

- copy source files directly into your project
- add SZTextView as a git submodule
- use carthage

i will close this issue for now. if anybody uncovers other details or solutions feel free to comment, reopen, whatever. thank you.

[cocoapods]: https://blog.cocoapods.org/CocoaPods-0.36/
[reject]: http://stackoverflow.com/a/35723091/683728
